docker tag rsyslog/rsyslog_dev_buildbot_suse:tumbleweed rsyslog/rsyslog_dev_buildbot_suse:tumbleweed_previous
docker push rsyslog/rsyslog_dev_buildbot_suse:tumbleweed_previous
#revert
#docker tag rsyslog/rsyslog_dev_buildbot_suse:tumbleweed_previous rsyslog/rsyslog_dev_buildbot_suse:tumbleweed
