.\" Copyright 2005 Rainer Gerhards and Adiscon for the rsyslog modifications
.\" Distributed under the GNU General Public License.
.\"
.TH RSYSLOGD 8 "03 July 2007" "Version 1.14.2 (devel)" "Linux System Administration"
.SH NAME
rfc3195d \- RFC 3195 listener
.SH SYNOPSIS
.B rfc3195d
.RB [ " \-d " ]
.RB [ " \-p"
.IB socket 
]
.RB [ " \-r"
.IB port 
]
.RB [ " \-v " ]
.LP
.SH DESCRIPTION
.B Rfc3195d
is a utility for receiving syslog messages via RFC 3195. Both
RAW and COOKED profiles are supported (but COOKED only without
relay-specific PATH elements).
rfc3195d accepts messages via RFC 3195 and forwards them to
the local domain socket specified in the -p option
(/dev/log3195 by default). There, the messages can be picked up
by the system syslogd. While rfc3195d can work with any syslogd,
we highly recommend using
.B rsyslogd,
because it has special handling
for the messages forwarded by rfc3195d. To enable message 
reception in
.B rsyslogd,
use the "-a :/dev/log3195" command line
option (the colon in front of the socket name tells
.B rsyslogd
that the messages contain hostnames - this is vital to get the
right sender name into your logs).

.B Rfc3195d
currently has very limited functionality. Most importantly,
it does not allow to limit the senders it receives messages from.
Documentation is also very sparse. The situation should improve over
time as the rsyslog project is continously being enhanced.
.LP
.SH OPTIONS
.TP
.BI "\-p " "socket"
The socket the received messages are to be sent to. If not specified,
/dev/log3195 is used.
.TP
.BI "\-r " "port"
The listen port to use. If not specified, IANA-assigned port 601 is used.
.TP
.B "\-d"
Turns on debug mode.  In it, rfc3195d spits out diagnostic information
to stdout.
.TP
.B "\-v"
Print version and exit.
.SH SIGNALS
.B Rfc3195d
reacts to a set of signals.
.TP
.B SIGTERM
.B Rfc3195d
terminates.
.TP
.B SIGUSR1
.B Rfc3195d
terminates.
.LP
.SH SEE ALSO
.BR rsyslog.conf (5),
.BR rsyslogd (8)
.LP
.SH MORE INFORMATION
Is available on the project home page at http://www.rsyslog.com
.LP
.SH COLLABORATORS
Rfc3195d uses liblogging (http://www.liblogging.org) for RFC 3195
protocol handling.
.PD 0
.TP
Rainer Gerhards <rgerhards@adiscon.com>
.zZ
