sudo: required
services: docker
language: minimal

install:
  - docker pull rsyslog/rsyslog_doc_gen

script:
  - docker run -e SPHINX_EXTRA_OPTS=-q
        -v "$PWD":/rsyslog-doc -ti
        rsyslog/rsyslog_doc_gen
